--- 
rdf_connection_file: rdfstore
local_uri: k
thumb_options: 
  height: "128"
  width: "128"
convert_command: /opt/local/bin/convert
standalone_db: false
exist_options: 
  community: my community
  exist_login: exist username
  exist_password: exist password
  exist_namespace: http://trac.talia.discovery-project.eu/wiki/Exist#
  server_url: exist server
db_file: database
namespaces: 
  dcns: http://purl.org/dc/elements/1.1/
  luccadom: http://trac.talia.discovery-project.eu/wiki/LuccaOntology#
  talias: http://trac.talia.discovery-project.eu/wiki/StructuralOntology#
  dct: http://purl.org/dc/terms/
  dcmit: http://purl.org/dc/dcmitype/
  taliadom: http://trac.talia.discovery-project.eu/wiki/SampleDomainOntology#
  foaf: http://xmlns.com/foaf/0.1/
  hyper: http://trac.talia.discovery-project.eu/wiki/HyperOntology#
default_namespace_uri: http://default.dummy/
start_page_editions: 
- facsimile
- critical
- categories
- series
iip_server_uri: http://localhost:/fcgi-bin/iipsrv.fcgi
auto_ontologies: ontologies
vips_command: /opt/local/bin/vips
