--- 
dyno: false
local_uri: http://isalmicart.muruca.org/
default_namespace_uri: http://default.dummy/
rdf_connection_file: rdfstore
ardf_log_level: 0
standalone_db: true
db_file: database
namespaces: 
  hyper: http://www.hypernietzsche.org/ontology/
  foaf: http://xmlns.com/foaf/0.1/
  skos: http://www.w3.org/2004/02/skos/core#
  dct: http://purl.org/dc/terms/
  dcmit: http://purl.org/dc/dcmitype/
  dcns: http://purl.org/dc/elements/1.1/
  luccadom: http://trac.talia.discovery-project.eu/wiki/LuccaOntology#
  talias: http://trac.talia.discovery-project.eu/wiki/StructuralOntology#
  taliadom: http://trac.talia.discovery-project.eu/wiki/SampleDomainOntology#
  sesame: http://www.openrdf.org/schema/sesame#
  swicky: http://discovery-project.eu/ontologies/philoSpace/
  discovery: http://discovery-project.eu/ontologies/scholar/0.1/
  marcont: http://www.marcont.org/ontology/2.1/
  wordnet: http://xmlns.com/wordnet/1.6/
  geo: http://www.w3.org/2003/01/geo/wgs84_pos#
  demo: http://ontologies.muruca.org/demo3#
  gnames: http://www.geonames.org/ontology#
  frbr: http://purl.org/vocab/frbr/core#
site_name: TALIA DEMO3
iip_root_directory_location: /opt/talia/data/islamicart_data/iip_root
data_directory_location: /opt/talia/data/islamicart_data/data
iip_server_uri: http://localhost:/fcgi-bin/iipsrv.fcgi
vips_command: /usr/bin/vips
convert_command: /usr/bin/convert
googlemap_key: ABQIAAAAOY6Zv9NunttIT5fALwpiRhSPtRO-56uzZJvIGXQxlGNVk-r4kxRE8NIB3lUS5Sog8714vby5L9bupQ
oai:
  prefix: oai:talia
  repository_name: Talia OAI Interface
shown_tabs:
  - users
  - talia_sources

thumb_options:
  height: "400"
  width: "400"
admin_email: admin@example.com